In [1]:
%%time

from functools import partial
from collections import defaultdict, namedtuple
import numpy as np
import pandas as pd
import scipy
from sklearn.model_selection import KFold
from tqdm.notebook import tqdm
from itertools import product

from video699.screen.semantic_segmentation.fastai_detector import *
from video699.screen.semantic_segmentation.common import *
from video699.screen.semantic_segmentation.postprocessing import *
from video699.screen.semantic_segmentation.evaluation import *

CPU times: user 5.7 s, sys: 952 ms, total: 6.65 s
Wall time: 6.76 s

In [6]:
detector = FastAIScreenDetector()
method_params = list(detector.methods.keys())
train_params = list(detector.train_params.keys())
all_params = train_params + method_params

# MODEL PARAMETERS

batch_size = [8]
resize_factor = [2]
frozen_epochs = [2, 6, 9]
unfrozen_epochs = [3, 7, 10]
frozen_lr = [1e-3]
unfrozen_lr = [slice(1e-4, 2e-4)]

train_params_values = [batch_size] + [resize_factor] + [frozen_epochs] + [unfrozen_epochs] + [frozen_lr] + [unfrozen_lr]

# POST PROCESSING PARAMETERS
base = [True]
base_lower_bounds = [7, 10]
base_upper_bounds = [30, 40, 50, 60, 70]
base_factors = [[0.1, 0.01]]

erode_dilate = [True]
erode_dilate_lower_bounds = [5]
erode_dilate_upper_bounds = [40]
erode_dilate_factors = [[0.1, 0.01]]
erode_dilate_iterations = [40, 100]

ratio_split = [True]
ratio_split_lower_bounds = [0.7, 0.9]
ratio_split_upper_bounds = [1.5]

methods_values = [base] + [erode_dilate] + [ratio_split] + [base_lower_bounds] + [base_upper_bounds] \
        + [base_factors] + [erode_dilate_lower_bounds] + [erode_dilate_upper_bounds] + [erode_dilate_factors] \
        + [erode_dilate_iterations] + [ratio_split_lower_bounds] + [ratio_split_upper_bounds]

In [7]:
method_settings = list(product(*methods_values))
train_settings = list(product(*train_params_values))
all_lectures = [video.filename for video in ALL_VIDEOS]
all_frames = [frame for video in ALL_VIDEOS for frame in video]
all_frames_grouped_by_videos = {video.filename: [frame for frame in video] for video in ALL_VIDEOS}
test_lectures = ['PB069-D2-20140305.mp4']
test_frames = [frame for lecture in test_lectures for frame in all_frames_grouped_by_videos[lecture]]
actual_detector = AnnotatedSampledVideoScreenDetector()

In [8]:
Split = namedtuple('Split', ['train', 'valid'])
kf = KFold(n_splits=5, shuffle=True, random_state=123)
splits = {}
for j, split in enumerate(kf.split(all_lectures)):    
    train_lectures = [all_lectures[index] for index in split[0]]
    valid_lectures = [all_lectures[index] for index in split[1]]
    valid_frames = [frame for lecture in valid_lectures for frame in all_frames_grouped_by_videos[lecture]]
    splits[j] = Split(train=train_lectures, valid=valid_lectures)

In [10]:
%%time
# Model selection
method_settings = list(product(*methods_values))
train_settings = list(product(*train_params_values))
df_all = pd.DataFrame(columns=all_params + ['iou', 'wrong_count', 'kfold_split'])

for train_setting in tqdm(train_settings):
    train_params_dict = dict(zip(train_params, train_setting))
    for j in splits.keys():
        train_lectures = splits[j].train
        valid_lectures = splits[j].valid
        valid_frames = [frame for lecture in valid_lectures for frame in all_frames_grouped_by_videos[lecture]]

        filtered_by = lambda name: any([lecture in str(name) for lecture in train_lectures + valid_lectures])  \
                        and 'frame' in str(name)
        split_by = lambda name: any([lecture in str(name) for lecture in valid_lectures])
        
        detector = FastAIScreenDetector(train_params=train_params_dict, methods=None, filtered_by=filtered_by,
                                    valid_func=split_by, device='cuda')
    
        detector.train()
        
        actuals = [actual_detector.detect(frame) for frame in valid_frames]
        sem_preds = detector.semantic_segmentation_batch(valid_frames)
        
        print(f"Iterating through {len(method_settings)} methods in split {j}.")    
        for i, method_setting in enumerate(method_settings):    
            preds = detector.post_processing_batch(sem_preds, valid_frames, dict(zip(method_params, method_setting)))
            wrong_count, ious, _ = evaluate(actuals, preds)
            
            iou_score = np.nanmean(ious)
            wrong_count = len(wrong_count)
            df_all.loc[len(df_all)] = train_setting + method_setting + (iou_score, wrong_count, j)

  0%|          | 0/9 [00:00<?, ?it/s]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 11%|█         | 1/9 [09:20<1:14:43, 560.39s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 22%|██▏       | 2/9 [24:20<1:17:17, 662.44s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 33%|███▎      | 3/9 [43:47<1:21:22, 813.77s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 44%|████▍     | 4/9 [58:41<1:09:48, 837.73s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 56%|█████▌    | 5/9 [1:19:09<1:03:38, 954.75s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 67%|██████▋   | 6/9 [1:43:52<55:39, 1113.19s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 78%|███████▊  | 7/9 [2:02:50<37:21, 1120.72s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

 89%|████████▉ | 8/9 [2:27:28<20:27, 1228.00s/it]

Iterating through 40 methods in split 0.

Iterating through 40 methods in split 1.

Iterating through 40 methods in split 2.

Iterating through 40 methods in split 3.

Iterating through 40 methods in split 4.

100%|██████████| 9/9 [2:56:24<00:00, 1176.01s/it]

CPU times: user 2h 8min 39s, sys: 32min 5s, total: 2h 40min 44s
Wall time: 2h 56min 24s

In [11]:
df_all.to_csv("model_selection.csv")